project_name: sample_1

input_data: "seurat_obj"   # input data type, either "seurat_obj" or "cell_ranger" 
input_location: "seurat.rds"  


results_dir: "./results/"

species: human 			# name of species either "mouse" or "human"

cell_ranger:
 min.cells: 3 			#keep genes expressed at least `min.cells`
 strip.suffix: True 		# Remove trailing '-1' in all cell barcodes

filtering:
 do_filtering: True      # if input_data: "seurat_obj" do subsetting, if input_data: "cell_ranger", do filtering
 nCount_RNA_min: 5000
 nCount_RNA_max: 100000
 nFeature_RNA_min: 2000
 nFeature_RNA_max: 10000
 percent.mt: 5	

subsetting:
 cell_label: seurat_clusters # cell grouping, can be cluster label or cell type or ...
 value: "all" # comma-separated groups to be included in the analysis. "all" means include all cells 

cell_cycle:
 do_analysis: True
 do_regression: all

normalization:
 do_normalization: True
 regress_mito: True

 n_variable_features: 3000

dim_reduction:
 do_PCA: True
 assay: SCT
 n_dims: 30

clustering:
 do_clustering: True
 knn : 30
 resolution: 0.1  # use "auto" for automatic determination of the number of clusters

UMAP:
 do_UMAP: True

markers:	
 find_markers : True
 min.pct : 0.25
 logfc.threshold : 0.5
 p_val_adj: 0.05
 #test.use : "LR" 
 #latent.vars : "sample"
 top_markers : 3
 GO_enrich: False

output_plots: 
 #generate_plots: False
 reduction: umap # choose name of Seurat's DimReduc object
 assay: RNA
 genesOfinterest_file : "genesOfinterest.txt"
 pointSize : 0.3

